name: Convert Excel to JSON

on:
  push:
    paths:
      - '*.xlsx'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas openpyxl

    - name: Convert Excel to JSON
      run: |
        python -c "
        import pandas as pd
        df = pd.read_excel('buku_dawis.xlsx')
        df.to_json('buku_dawis', orient='records', lines=True)
        "

    - name: Commit JSON file
      run: |
          git config --global user.email "doniphantom@gmai.com"
          git config --global user.name "doniphantom"
          git add buku_dawis.json
          git commit -m "Buku Dawis JSON"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
