name: Process Excel and Run Selenium Tests

on:
  # Memicu workflow saat repository_dispatch event diterima
  repository_dispatch:
    types: [custom-event] # Sesuaikan dengan jenis event yang kamu definisikan

  # Memicu workflow saat terjadi push ke branch tertentu, misalnya 'main'
  push:
    branches:
      - main

jobs:
  process_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver-manager
        pip install pandas
        pip install openpyxl
        pip install pytz
        # Install other dependencies if needed

    - name: Convert Excel to JSON
      run: |
        python -c "
        import pandas as pd
        df = pd.read_excel('buku_dawis.xlsx')
        df = df[['Desa', 'Dawis', 'KRT', 'Warga_TP_PPK']]  # Memilih kolom yang diperlukan
        df.to_json('excel_output.json', orient='records', indent=4)
        "

    - name: Save last execution date and time to JSON (WIB)
      run: |
        python -c "
        import json
        from datetime import datetime
        import pytz

        # Set timezone to Asia/Jakarta (WIB)
        timezone = pytz.timezone('Asia/Jakarta')
        now = datetime.now(timezone)

        data = {
            'last_execution': now.strftime('%Y-%m-%d %H:%M:%S WIB')
        }

        with open('tanggal.json', 'w') as f:
            json.dump(data, f, indent=4)
        "

    - name: Run Selenium scripts
      run: |
        python jsonselenium.py
        python wargajiwa.py

    - name: Commit JSON files to GitHub Pages
      run: |
        git config --global user.email "doniphantom@gmail.com"
        git config --global user.name "doniphantom"
        git add tanggal.json
        git add excel_output.json
        git add output.json
        git commit -m "Update JSON files from Excel and Selenium"
        git push origin main --force
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
