name: Selenium Test

on:
  # push:
  #   branches:
  #     - main
  repository_dispatch:
    types: [post-http]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install webdriver-manager
          pip install pandas
          # Install other dependencies if needed

      - name: Run Selenium script
        run: |
          python jsonselenium.py

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v3
        with:
          name: selenium-output
          path: output.json

      - name: Commit JSON to GitHub Pages
        run: |
          git config --global user.email "doniphantom@gmai.com"
          git config --global user.name "doniphantom"
          git add output.json
          git commit -m "Update JSON output"
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
