name: Process Excel and Run Selenium Tests

on:
  push:
    branches:
      - main
    paths:
      - '*.xlsx'
  repository_dispatch:
    types: [trigger-event]

jobs:
  process_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install webdriver-manager
        pip install pandas
        # Install other dependencies if needed

    - name: Convert Excel to JSON
      run: |
        python -c "
        import pandas as pd
        df = pd.read_excel('buku_dawis.xlsx')
        df.to_json('excel_output.json', orient='records', lines=True)
        "

    - name: Run Selenium scripts
      run: |
        python jsonselenium.py
        python wargajiwa.py

    - name: Commit JSON files to GitHub Pages
      run: |
        git config --global user.email "doniphantom@gmail.com"
        git config --global user.name "doniphantom"
        git add excel_output.json
        git add output.json
        git commit -m "Update JSON files from Excel and Selenium"
        git push origin main --force
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
